# KM {#p02}

```{r 'P02-R', decorate=TRUE, include=FALSE, cache=FALSE}
sys.source(here::here("code", "A00Knitr.R"), envir = knitr::knit_global())
sys.source(here::here("code", "A01Packages.R"), envir = knitr::knit_global())
sys.source(here::here("code", "A02AllUDF.R"), envir = knitr::knit_global())
reticulate::source_python(here::here("code", "B01Modules.py"), convert = FALSE)
sys.source(here::here("code", "A04PackagesPython.R"), envir = knitr::knit_global())
if(FALSE) knit_exit() #Evaluate only up to this chunk and complete the knit process
```

## KM Network

\textcolor{pink}{Please import the "P01-KM-Week1.xlsx" and "P01-KM-Week4.xlsx"}

- About: Edges and Vertices of a Class Network at Week 1 and Week 4

```{r 'P02-R-XL-KM', decorate=TRUE, include=FALSE}
loc_rds <- here("data", "P01-R-KM-Week1.rds")
stopifnot(file.exists(loc_rds))
p02r_km_1 <- readRDS(loc_rds)
loc_rds <- here("data", "P01-R-KM-Week4.rds")
stopifnot(file.exists(loc_rds))
p02r_km_4 <- readRDS(loc_rds)
```

```{r 'P02-R-Dimensions-KM', decorate=TRUE}
# #Dimensions of Each Sheet: Row 1 (Rows), Row 2 (Columns), Columns (Sheets)
vapply(p02r_km_1, dim, numeric(2))
vapply(p02r_km_4, dim, numeric(2))
# #Structure
if(FALSE) str(p02r_km_1)
if(FALSE) str(p02r_km_4)
# #Summary of List Objects
if(FALSE) lapply(p02r_km_1, summary)
if(FALSE) lapply(p02r_km_4, summary)
```



## Validation {#val-p01 .unlisted .unnumbered .tabset .tabset-fade}

```{r 'P02-R-Cleanup', decorate=TRUE, include=FALSE, cache=FALSE}
if(FALSE) f_rmExist(aa)
```

```{r 'P02-R-Validation', decorate=TRUE, include=TRUE, cache=FALSE}
# #SUMMARISED Packages and Objects (BOOK CHECK)
f_()
#
difftime(Sys.time(), q_start)
```

****
